logitech-ms-container:
  image: 'docker.io/larsks/logitech-media-server'
  container_name: "APP_IDENTIFIER"
  restart: unless-stopped
  ports:
    - '9002:9000'
    - '3484:3483/udp'
  volumes:
    - '/etc/localtime:/etc/localtime:ro'
    - './squeezebox:/srv/squeezebox'
    - './audio:/srv/music'
