portainer-container:
  image: 'docker.io/portainer/portainer'
  container_name: "portainer"
  hostname: "portainer.example.com"
  restart: unless-stopped
  ports:
    - '9001:9000'
  volumes:
    - '/var/run/docker.sock:/var/run/docker.sock'
